import type { Metadata } from "next";
import { Suspense } from "react";
import { headers } from "next/headers";
import ReactQueryProvider from "@/providers/react-query";
import { ThemeProvider } from "@/providers/theme";
import { THEME_STORAGE_KEY } from "@/lib/theme-storage-key";
import { Manrope, DM_Mono } from "next/font/google";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { GlobalInit } from "@/lib/global-init";
import { AnalyticsTracker } from "@/components/analytics-tracker";
import { ServiceWorkerRegister } from "@/components/sw-register";

const metadataBaseUrl = (() => {
  try {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL;
    return appUrl ? new URL(appUrl) : new URL("http://localhost:3000");
  } catch {
    return new URL("http://localhost:3000");
  }
})();

export const metadata: Metadata = {
  metadataBase: metadataBaseUrl,
  title: {
    default: "GhostClass | Smart Attendance Tracker",
    template: "%s | GhostClass",
  },
  description: "GhostClass — Survive Attendance!",
  keywords:
    "GhostClass, bunk college, bunk, college attendance, skip lectures, 75% attendance, bunkr, bunk lectures, Bunkr attendance calculator, skip class calculator for college, Bunkr Ezygo alternative, optimize college attendance percentage, Bunkr smart skip strategy, minimum attendance calculator for students, Bunkr class absence planner, how many classes can I skip Bunkr, attendance percentage tracker app, Bunkr vs Ezygo comparison, automate student attendance tracking, Bunkr attendance predictor, avoid attendance shortage Bunkr, college attendance skip allowance, Bunkr attendance optimizer, student absence management app, calculate class skip limit Bunkr, Bunkr attendance analytics dashboard, best app to skip college classes, Bunkr digital roll call system, attendance risk calculator for students",
  creator: "@deva.kesu",
  openGraph: {
    title: "GhostClass | Smart Attendance Tracker",
    description: "GhostClass — Survive Attendance!",
    url: process.env.NEXT_PUBLIC_APP_URL,
    siteName: "GhostClass",
    images: [{ url: "/opengraph-image", width: 1200, height: 630 }],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "GhostClass",
    description: "Bunk college smartly with GhostClass.",
    images: ["/opengraph-image"],
  },
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    apple: '/apple-icon',
  },
  manifest: '/manifest.webmanifest',
};

const klick = localFont({
  src: "./fonts/Klick.woff2",
  variable: "--font-klick",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-mono",
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
});


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ⚠️  CRITICAL — DO NOT REMOVE THIS CALL.
  // Calling headers() makes this layout dynamic (per-request) so that Next.js reads
  // the x-nonce generated by src/proxy.ts on every request. Without it, Next.js may
  // statically cache the layout; getCspHeader() would be invoked without a nonce and
  // CSP degrades to 'unsafe-inline' for all pages, silently disabling XSS protection.
  // The x-nonce header is read here and forwarded to the inline script for strict-CSP
  // compliance. If this layout is ever refactored, verify nonce delivery end-to-end
  // before merging.
   
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  const gaId = process.env.NEXT_PUBLIC_GA_ID;
  const hasGoogleAnalytics = !!gaId && gaId !== 'undefined' && gaId.startsWith('G-');
  
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth" className="dark">
      <head>
        {/* Blocking script: executes synchronously before any CSS or content is
            painted. Measures the real scrollbar track width by creating a hidden
            div with forced scrollbar (offsetWidth - clientWidth), then sets
            --scrollbar-width on :root. This is independent of CSS load order
            and of scrollbar-gutter, unlike calc(100vw - 100%) tricks.
            A ResizeObserver keeps the value current on zoom / display changes.
            CSP nonce is required for strict-CSP compliance. */}
        <script
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('${THEME_STORAGE_KEY}');var n=t==='light'||t==='dark'?t:'dark';if(n==='light'){document.documentElement.classList.remove('dark')}else{document.documentElement.classList.add('dark')}var m=document.querySelector('meta[name="theme-color"]');if(m)m.setAttribute('content',n==='dark'?'#141414':'#f8f8fc')}catch(e){document.documentElement.classList.add('dark')}function u(){var d=document.createElement('div');d.style.cssText='position:absolute;top:-9999px;width:99px;height:99px;overflow:scroll';document.documentElement.appendChild(d);var w=d.offsetWidth-d.clientWidth;d.remove();document.documentElement.style.setProperty('--scrollbar-width',w+'px')}u();if(typeof ResizeObserver!=='undefined'){new ResizeObserver(function(){u()}).observe(document.documentElement)}else if(typeof window!=='undefined'&&window.addEventListener){window.addEventListener('resize',u)}})();`,
          }}
        />
        <meta name="application-name" content="GhostClass" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="msapplication-TileColor" content="#141414" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="theme-color" content="#141414" />
      </head>
      <body
        className={`overflow-x-hidden w-full max-w-screen antialiased ${klick.variable} ${manrope.variable} ${dmMono.variable}`}
      >
        {/* Pre-hydration loader — injected via script so React never owns this
            DOM node. Safe to imperatively .remove() from GlobalInit without
            corrupting React's fiber tree. */}
        <script nonce={nonce} suppressHydrationWarning dangerouslySetInnerHTML={{ __html: `
(function(){
  var wrap = document.createElement('div');
  wrap.id = 'prehyd-loader';
  wrap.setAttribute('role', 'status');
  wrap.setAttribute('aria-label', 'Loading, please wait');
  Object.assign(wrap.style, {
    position:'fixed', inset:'0', display:'flex', flexDirection:'column',
    alignItems:'center', justifyContent:'center', gap:'24px',
    background:'var(--background)', zIndex:'99999'
  });
  var ring = document.createElement('div');
  ring.setAttribute('aria-hidden', 'true');
  Object.assign(ring.style, {
    width:'38px', height:'38px', borderRadius:'50%',
    border:'3px solid rgba(168,85,247,0.15)', borderTopColor:'#a855f7',
    animation:'gc-spin 0.75s linear infinite'
  });
  var txt = document.createElement('p');
  txt.setAttribute('aria-hidden', 'true');
  Object.assign(txt.style, {
    margin:'0', fontFamily:'var(--font-manrope),sans-serif', fontSize:'15px',
    fontStyle:'italic', color:'var(--muted-foreground)',
    textAlign:'center', maxWidth:'280px', lineHeight:'1.5'
  });
  txt.textContent = '\u201cWaiting on Ezygo to stop ghosting us \uD83D\uDC7B\u201d';
  wrap.appendChild(ring);
  wrap.appendChild(txt);
  document.currentScript.parentNode.insertBefore(wrap, document.currentScript.nextSibling);
})();
        `}} />
        {/* Skip Navigation Link for Accessibility */}
        <a 
          href="#main-content" 
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-100000 focus:bg-background focus:text-foreground focus:px-4 focus:py-2 focus:rounded focus:ring-2 focus:ring-ring"
        >
          Skip to main content
        </a>
        <ThemeProvider>
        <ReactQueryProvider>
          {/* --- GOOGLE ANALYTICS (Server-side via Measurement Protocol) --- */}
          {/* AnalyticsTracker is placed inside ReactQueryProvider so it can safely */}
          {/* use TanStack Query hooks in the future without ordering issues.       */}
          {hasGoogleAnalytics && (
            <Suspense fallback={null}>
              {/* Client-side tracker component - sends events to /api/analytics/track */}
              {/* No gtag.js script needed - bypasses CSP inline script restrictions */}
              <AnalyticsTracker />
            </Suspense>
          )}
          <NextTopLoader 
            color="#a855f7"
            initialPosition={0.08}
            crawlSpeed={200}
            height={5}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow={false}
            zIndex={2147483647}
          />
          <GlobalInit />
          <ServiceWorkerRegister />
          <div id="main-content" tabIndex={-1} className="flex min-h-screen flex-col bg-background">
            {children}
          </div>
        </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}