#!/usr/bin/env node
/**
 * Build service worker for production
 * This script ensures the service worker is generated even in standalone mode
 */

const { build } = require("esbuild");
const fs = require("node:fs");
const path = require("node:path");

async function buildServiceWorker() {
  console.log("🔨 Building service worker...");

  const swSrc = path.join(__dirname, "../src/sw.ts");
  const swDest = path.join(__dirname, "../public/sw.js");

  // Check if source exists
  if (!fs.existsSync(swSrc)) {
    console.error(`❌ Service worker source not found at ${swSrc}`);
    process.exit(1);
  }

  try {
    // Build the TypeScript service worker to JavaScript
    await build({
      entryPoints: [swSrc],
      bundle: true,
      outfile: swDest,
      format: "iife",
      target: "es2020",
      minify: process.env.NODE_ENV === "production",
      define: {
        "process.env.NODE_ENV": JSON.stringify(
          process.env.NODE_ENV || "production",
        ),
      },
      banner: {
        js: "// Service Worker - Generated by build-sw.js",
      },
    });

    console.log(`✅ Service worker built successfully at ${swDest}`);

    // Verify the file exists and has content
    const stats = fs.statSync(swDest);
    console.log(`   Size: ${(stats.size / 1024).toFixed(2)} KB`);
  } catch (error) {
    console.error("❌ Failed to build service worker:", error);
    process.exit(1);
  }
}

buildServiceWorker();
