import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";
import { getCspHeader } from "./lib/csp";
import { TERMS_VERSION } from "./app/config/legal";
import { logger } from "./lib/logger";

/**
 * Clears all session-related cookies on a redirect response.
 * Deletes custom app cookies plus the Supabase SSR auth cookie (including
 * any chunked variants) derived from NEXT_PUBLIC_SUPABASE_URL.
 * Call this on every logout/unauthenticated-redirect path so that adding a
 * new session cookie only requires a change here, not in every branch.
 *
 * NOTE: csrf_token is intentionally NOT cleared here. The CSRF token is a
 * browser-tab nonce — it is not tied to any specific user identity and does
 * not carry session state. Clearing it on every unauthenticated redirect
 * would leave the subsequent login attempt without a valid cookie if the
 * 30-minute per-tab throttle in useCSRFToken is still active, causing a
 * 403 on the next CSRF-protected request (e.g. /api/auth/save-token).
 * csrf_token is only cleared by the explicit logout handler via removeCsrfToken().
 */
function clearSessionCookies(res: NextResponse, request: NextRequest) {
  res.cookies.delete('ezygo_access_token');
  res.cookies.delete('terms_version');
  res.cookies.delete('terms_redirect_count');
  try {
    const projectRef = new URL(process.env.NEXT_PUBLIC_SUPABASE_URL ?? "").hostname.split(".")[0];
    if (projectRef) {
      const sbCookieName = `sb-${projectRef}-auth-token`;
      res.cookies.delete(sbCookieName);
      for (const c of request.cookies.getAll()) {
        if (c.name.startsWith(`${sbCookieName}.`)) {
          res.cookies.delete(c.name);
        }
      }
    }
  } catch {
    // Non-critical: cookie expiry handles it naturally
  }
}

/**
 * Creates a cryptographically secure nonce for CSP.
 * Uses Web Crypto API for compatibility with both Node.js and Edge runtimes.
 */
function createNonce() {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  // Convert to base64 using btoa and proper string conversion
  // This works in both Node.js (v20+) and Edge runtime
  return btoa(String.fromCharCode(...bytes));
}

function isRefreshTokenNotFoundError(error: unknown): boolean {
  if (!error || typeof error !== "object") {
    return false;
  }

  const authError = error as { code?: unknown; status?: unknown; message?: unknown };
  return authError.code === "refresh_token_not_found"
    || (authError.status === 400 && typeof authError.message === "string" && authError.message.includes("Invalid Refresh Token"));
}

export async function proxy(request: NextRequest) {
  const nonce = createNonce();
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce", nonce);
  const isNavigationRequest = request.method === "GET" || request.method === "HEAD";
  const redirectStatus = isNavigationRequest ? 307 : 303;

  // 1. Get CSP Header
  const cspHeader = getCspHeader(nonce);

  // 2. Initialize Response with nonce in headers for Next.js to use
  let response = NextResponse.next({
    request: { 
      headers: requestHeaders 
    },
  });

  // 3. Apply CSP to the initial response
  // x-nonce is attached to the *request* (see requestHeaders + NextResponse.next above)
  // so that Next.js Server Components can read it via headers() and inject it into inline
  // <script>/<style> tags (e.g., in layout.tsx). We also mirror it on the response header.
  //
  // /api-docs uses @scalar/nextjs-api-reference which renders a standalone HTML page that
  // loads its runtime from cdn.jsdelivr.net. This external CDN is not in the standard app
  // CSP. We apply a dedicated, relaxed CSP only for this documentation route so the Scalar
  // viewer can load while the rest of the app remains under strict CSP.
  const pathname = request.nextUrl.pathname;
  const isApiDocs = pathname === '/api-docs' || pathname.startsWith('/api-docs/');
  const effectiveCspHeader = isApiDocs
    ? [
        "default-src 'self'",
        // Scalar renders an inline <script> for its init call (createApiReference),
        // so 'unsafe-inline' is required for scripts on this route. Adding a nonce
        // is not viable because the HTML is generated by @scalar/nextjs-api-reference
        // and we cannot inject the per-request nonce into Scalar's output.
        "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
        "script-src-elem 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
        "style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com",
        "font-src 'self' data: https://fonts.gstatic.com",
        "img-src 'self' data: blob: https://cdn.jsdelivr.net",
        // Narrowed from https: — Scalar only needs to reach its CDN bundle.
        "connect-src 'self' https://cdn.jsdelivr.net",
        "worker-src 'self' blob:",
        "frame-ancestors 'none'",
        "object-src 'none'",
        "base-uri 'self'",
      ].join("; ")
    : cspHeader;
  response.headers.set('Content-Security-Policy', effectiveCspHeader);
  response.headers.set("x-nonce", nonce);

  // 4. Initialize Supabase
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          response = NextResponse.next({ request: { headers: requestHeaders } });
          
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          );

          // ⚠️ CRITICAL: Re-apply CSP and nonce to the new response
          response.headers.set('Content-Security-Policy', effectiveCspHeader);
          response.headers.set("x-nonce", nonce);
        },
      },
    }
  );

  // 5. Refresh Session
  let user: Awaited<ReturnType<typeof supabase.auth.getUser>>["data"]["user"] = null;
  try {
    const { data, error } = await supabase.auth.getUser();
    if (error) {
      if (isRefreshTokenNotFoundError(error)) {
        // Invalid refresh token — treat as unauthenticated. Do NOT clear
        // session cookies here: clearSessionCookies() must only run on
        // redirect responses (Scenarios A / logout-loop below). Calling it
        // on the pass-through response for public-route requests (RSC fetches
        // for /help, /legal, etc.) would delete csrf_token and other cookies
        // that are still valid and unrelated to the Supabase session.
        // The redirect-path in Scenario A already calls clearSessionCookies()
        // when the user later tries to reach a protected route.
      } else {
        logger.warn("Supabase auth refresh failed in proxy; proceeding unauthenticated.", { error });
        // Transient error — proceed as unauthenticated without touching cookies.
      }
    } else {
      user = data.user;
    }
  } catch (error) {
    logger.warn("Supabase auth getUser threw unexpectedly in proxy; proceeding unauthenticated.", { error });
    // Unexpected error — proceed as unauthenticated without touching cookies.
  }

  // 6. Routing Logic
  const termsVersion = request.cookies.get("terms_version")?.value;
  const isDashboardRoute = request.nextUrl.pathname.startsWith("/dashboard");
  const isProfileRoute = request.nextUrl.pathname.startsWith("/profile");
  const isNotificationsRoute = request.nextUrl.pathname.startsWith("/notifications");
  const isTrackingRoute = request.nextUrl.pathname.startsWith("/tracking");
  const isScoresRoute = request.nextUrl.pathname.startsWith("/scores");
  const isAuthRoute = request.nextUrl.pathname === "/";
  const isAcceptTermsRoute = request.nextUrl.pathname === "/accept-terms";

  // Protected routes that require authentication and terms acceptance
  const isProtectedRoute = isDashboardRoute || isProfileRoute || isNotificationsRoute || isTrackingRoute || isScoresRoute;

  // Scenario A: Unauthenticated users cannot access protected routes or accept-terms page
  if (!user && (isProtectedRoute || isAcceptTermsRoute)) {
    const url = request.nextUrl.clone();
    url.pathname = "/";
    const redirectRes = NextResponse.redirect(url, { status: redirectStatus });
    redirectRes.headers.set('Content-Security-Policy', cspHeader);
    redirectRes.headers.set("x-nonce", nonce);
    // No valid Supabase session — wipe all session cookies so stale state from
    // a previous user cannot be inherited by the next user on the same device.
    clearSessionCookies(redirectRes, request);
    return redirectRes;
  }

  // Scenario B: Logged in but terms not accepted or outdated -> Redirect to Accept Terms
  // Note: /accept-terms requires authentication (handled in Scenario A.1), but is accessible with outdated/missing terms
  // Explicitly check for null/undefined termsVersion or version mismatch
  if (user && (!termsVersion || termsVersion !== TERMS_VERSION) && isProtectedRoute) {
    // Before redirecting, check the DB — the user may have accepted terms on another device.
    // This query is only reached when the cookie is missing or stale, so it doesn't add
    // overhead to normal authenticated requests.
    try {
      const { data: userProfile, error: userProfileError } = await supabase
        .from("users")
        .select("terms_version")
        .eq("auth_id", user.id)
        .single();

      if (userProfileError) {
        throw userProfileError;
      }

      if (userProfile?.terms_version === TERMS_VERSION) {
        // Accepted elsewhere — sync cookie to this device and allow through.
        response.cookies.set("terms_version", TERMS_VERSION, {
          httpOnly: true,
          secure: process.env.HTTPS === 'true' || process.env.NODE_ENV === 'production',
          sameSite: "lax",
          path: "/",
          maxAge: 31536000, // 1 year
        });
        response.cookies.delete("terms_redirect_count");
        return response;
      }
    } catch (dbError) {
      // Non-fatal: if the DB check fails, fall through to the normal redirect flow.
      logger.warn("Failed to check terms_version from DB in proxy; falling back to cookie check.", { dbError });
    }

    const url = request.nextUrl.clone();
    
    // Redirect loop protection: use httpOnly cookie to track redirect attempts
    // This prevents manipulation via URL parameters which could be exploited for DoS
    const redirectCountCookie = request.cookies.get('terms_redirect_count');
    const raw = redirectCountCookie?.value;
    const redirectCount = (raw && /^\d+$/.test(raw)) ? parseInt(raw, 10) : 0;
    
    if (redirectCount >= 3) {
      // Too many redirect attempts — force-clear all session cookies and send to login.
      // Redirecting to a non-existent /logout page would 404; we clear state here directly
      // instead. Client-side storage (localStorage and sessionStorage) will be cleared by handleLogout when
      // ProtectedLayout detects the missing session on the next protected-route visit.
      logger.warn('Terms acceptance redirect loop detected. Logging user out.', {
        redirectCount,
        termsVersion: termsVersion || 'none',
        expectedVersion: TERMS_VERSION
      });

      const homeUrl = url.clone();
      homeUrl.pathname = '/';
      homeUrl.search = '';
      const logoutRes = NextResponse.redirect(homeUrl, { status: redirectStatus });
      logoutRes.headers.set('Content-Security-Policy', cspHeader);
      logoutRes.headers.set("x-nonce", nonce);
      clearSessionCookies(logoutRes, request);
      return logoutRes;
    }
    
    url.pathname = "/accept-terms";
    const redirectRes = NextResponse.redirect(url, { status: redirectStatus });
    redirectRes.headers.set('Content-Security-Policy', cspHeader);
    redirectRes.headers.set("x-nonce", nonce);
    // Increment redirect count in httpOnly cookie (secure, non-manipulable)
    redirectRes.cookies.set('terms_redirect_count', String(redirectCount + 1), {
      httpOnly: true,
      secure: process.env.HTTPS === 'true' || process.env.NODE_ENV === 'production',
      sameSite: 'strict',
      path: '/',
      maxAge: 300, // 5 minutes - enough for legitimate redirects, prevents long-term accumulation
    });
    return redirectRes;
  }

  // Scenario C: Terms accepted but on accept-terms page -> Redirect to Dashboard
  if (user && termsVersion === TERMS_VERSION && isAcceptTermsRoute && isNavigationRequest) {
    const url = request.nextUrl.clone();
    url.pathname = "/dashboard";
    const redirectRes = NextResponse.redirect(url, { status: redirectStatus });
    redirectRes.headers.set('Content-Security-Policy', cspHeader);
    redirectRes.headers.set("x-nonce", nonce);
    // Clear the redirect count cookie after successful terms acceptance
    redirectRes.cookies.delete('terms_redirect_count');
    return redirectRes;
  }

  // Scenario D: Logged in -> Redirect to Dashboard
  if (user && isAuthRoute) {
    const url = request.nextUrl.clone();
    url.pathname = "/dashboard";
    const redirectRes = NextResponse.redirect(url, { status: redirectStatus });
    redirectRes.headers.set('Content-Security-Policy', cspHeader);
    redirectRes.headers.set("x-nonce", nonce);
    // Clear redirect count so a fresh login doesn't inherit a stale counter
    // from a previous terms-redirect loop on the same device.
    redirectRes.cookies.delete('terms_redirect_count');
    return redirectRes;
  }

  return response;
}

export const config = {
  // Match all routes except:
  // - Static assets (_next/static, _next/image, favicon.ico, robots.txt)
  // - API routes (handled separately with their own auth)
  // - Public PWA/static files that must never trigger auth session logic
  //
  // This simplified matcher pattern uses a negative lookahead regex to exclude specific paths.
  // Any new routes will automatically have CSP headers and Supabase session refresh applied.
  //
  // Pattern explanation: /((?!api|_next/static|_next/image|favicon.ico|favicon.svg|robots.txt|monitoring|manifest.webmanifest|sw.js|icon-|logo.png).*)
  // - Matches all paths that DON'T START with the listed prefixes/names
  // - The negative lookahead (?!...) is evaluated at match time to exclude specific paths
  //
  // This ensures middleware runs on all page routes for proper security headers and auth handling.
  // Public routes like /health are under /api and are excluded by the 'api' pattern.
  //
  // ⚠️ IMPORTANT: Public static files in /public (manifest.webmanifest, sw.js, icons) MUST be
  // excluded here. The middleware calls supabase.auth.getUser() on every matched request, which
  // is a live network call. Having it run on every PWA manifest or icon fetch is wasteful and
  // can create race conditions with cookie mutations on response objects. These files are static
  // and never need auth session logic or CSP headers.
  // If you need to add more exclusions (e.g., /sitemap.xml), add them to the pattern below.
  matcher: [
    // Exclude monitoring (Sentry tunnel) from middleware processing.
    // The Sentry SDK can burst 100+ POST requests/sec to /monitoring;
    // running the full middleware (supabase.auth.getUser(), CSP generation,
    // routing logic) for each one overwhelms the server and blocks SSR
    // streaming for actual page navigations — especially on Android PWA
    // standalone launch where the burst compounds with SW lifecycle events.
    "/((?!api|_next/static|_next/image|favicon.ico|favicon.svg|robots.txt|monitoring|manifest.webmanifest|sw.js|icon-|logo.png).*)",
  ],
};