


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "hypopg" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "index_advisor" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."check_225_attendance_limit"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET search_path = public, pg_temp
    AS $$
DECLARE
  attendance_225_count INTEGER;
BEGIN
  -- Only check if attendance is 225
  IF NEW.attendance != 225 THEN
    RETURN NEW;
  END IF;

  -- Count existing 225 attendance records for this course in this semester/year
  SELECT COUNT(*)
  INTO attendance_225_count
  FROM public.tracker
  WHERE auth_user_id = NEW.auth_user_id
    AND course = NEW.course
    AND semester = NEW.semester
    AND year = NEW.year
    AND attendance = 225
    AND id != COALESCE(NEW.id, 0); -- Exclude current record for updates

  -- Enforce limit
  IF attendance_225_count >= 5 THEN
    RAISE EXCEPTION 'Maximum 5 Duty Leaves exceeded for course: %', NEW.course
      USING HINT = 'Only 5 duty leaves allowed per semester per course';
  END IF;

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."check_225_attendance_limit"() OWNER TO "postgres";


COMMENT ON FUNCTION "public"."check_225_attendance_limit"() IS 'Enforces maximum 5 DLs per semester per course';



CREATE OR REPLACE FUNCTION "public"."delete_user_account"() RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  requesting_user_id uuid;
begin
  -- Get the ID of the user calling the function
  requesting_user_id := auth.uid();

  if requesting_user_id is null then
    raise exception 'Not authenticated';
  end if;

  -- 1. [NEW] Delete Storage Objects (Avatars, etc.)
  -- This removes all files owned by this user from ALL buckets (e.g., 'avatars')
  delete from storage.objects where owner = requesting_user_id;

  -- 2. Delete form public tables (Order matters due to foreign keys)
  delete from public.tracker where auth_user_id = requesting_user_id;
  delete from public.notification where auth_user_id = requesting_user_id;
  delete from public.user_settings where user_id = requesting_user_id;
  
  -- 3. Delete the public profile
  delete from public.users where auth_id = requesting_user_id;

  -- 4. Finally, delete the auth user itself
  delete from auth.users where id = requesting_user_id;
end;
$$;


ALTER FUNCTION "public"."delete_user_account"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."contact_messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "subject" "text",
    "message" "text" NOT NULL,
    "status" "text" DEFAULT 'new'::"text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."contact_messages" OWNER TO "postgres";


COMMENT ON TABLE "public"."contact_messages" IS 'Stores Contact Messages';



CREATE TABLE IF NOT EXISTS "public"."notification" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "topic" "text" NOT NULL,
    "is_read" boolean DEFAULT false,
    "auth_user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."notification" OWNER TO "postgres";


COMMENT ON TABLE "public"."notification" IS 'Stores User Notifications';



ALTER TABLE "public"."notification" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notification_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tracker" (
    "id" bigint NOT NULL,
    "course" "text" NOT NULL,
    "date" "date" NOT NULL,
    "session" "text" NOT NULL,
    "semester" "text" NOT NULL,
    "year" "text" NOT NULL,
    "status" "text" DEFAULT 'correction'::"text" NOT NULL,
    "attendance" numeric DEFAULT '110'::numeric NOT NULL,
    "remarks" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "auth_user_id" "uuid" NOT NULL,
    CONSTRAINT "tracker_status_check" CHECK (("status" = ANY (ARRAY['correction'::"text", 'extra'::"text"])))
);


ALTER TABLE "public"."tracker" OWNER TO "postgres";


COMMENT ON TABLE "public"."tracker" IS 'Stores User-added Attendance Tracking Records';



ALTER TABLE "public"."tracker" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tracker_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_settings" (
    "user_id" "uuid" NOT NULL,
    "bunk_calculator_enabled" boolean DEFAULT true,
    "target_percentage" integer DEFAULT 75,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."user_settings" OWNER TO "postgres";


COMMENT ON TABLE "public"."user_settings" IS 'Stores User Settings';



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "username" "text" NOT NULL,
    "email" "text",
    "phone" "text",
    "avatar_url" "text",
    "first_name" "text",
    "last_name" "text",
    "birth_date" "text",
    "gender" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ezygo_token" "text",
    "ezygo_iv" "text",
    "last_synced_at" timestamp with time zone,
    "auth_id" "uuid",
    "terms_accepted_at" timestamp with time zone,
    "terms_version" "text",
    "auth_password" "text",
    "auth_password_iv" "text",
    CONSTRAINT "check_auth_password_consistency" CHECK (((("auth_password" IS NULL) AND ("auth_password_iv" IS NULL)) OR (("auth_password" IS NOT NULL) AND ("auth_password_iv" IS NOT NULL)))),
    CONSTRAINT "check_auth_password_iv_not_empty" CHECK ((("auth_password_iv" IS NULL) OR ("auth_password_iv" <> ''::"text"))),
    CONSTRAINT "check_auth_password_not_empty" CHECK ((("auth_password" IS NULL) OR ("auth_password" <> ''::"text")))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON TABLE "public"."users" IS 'Stores User Information';



ALTER TABLE ONLY "public"."contact_messages"
    ADD CONSTRAINT "contact_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notification"
    ADD CONSTRAINT "notification_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tracker"
    ADD CONSTRAINT "tracker_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tracker"
    ADD CONSTRAINT "unique_attendance_slot" UNIQUE ("auth_user_id", "course", "date", "session");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_phone_key" UNIQUE ("phone");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");



CREATE INDEX "idx_contact_created" ON "public"."contact_messages" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_contact_messages_user" ON "public"."contact_messages" USING "btree" ("user_id");



CREATE INDEX "idx_contact_status_created" ON "public"."contact_messages" USING "btree" ("status", "created_at" DESC);



COMMENT ON INDEX "public"."idx_contact_status_created" IS 'Speeds up admin queries for filtering contact messages by status';



CREATE INDEX "idx_notification_topic_unread" ON "public"."notification" USING "btree" ("auth_user_id", "topic", "is_read", "created_at" DESC) WHERE ("is_read" = false);



COMMENT ON INDEX "public"."idx_notification_topic_unread" IS 'Optimizes queries for unread notification counts grouped by topic';



CREATE INDEX "idx_notification_unread" ON "public"."notification" USING "btree" ("auth_user_id", "created_at" DESC) WHERE ("is_read" = false);



COMMENT ON INDEX "public"."idx_notification_unread" IS 'Optimizes queries for unread notifications (most common use case)';



CREATE INDEX "idx_notification_user_read_created" ON "public"."notification" USING "btree" ("auth_user_id", "is_read", "created_at" DESC);



COMMENT ON INDEX "public"."idx_notification_user_read_created" IS 'Optimizes queries for all notifications with read status filter';



CREATE INDEX "idx_tracker_course_date" ON "public"."tracker" USING "btree" ("course", "date" DESC) WHERE ("auth_user_id" IS NOT NULL);



COMMENT ON INDEX "public"."idx_tracker_course_date" IS 'Improves performance for course-specific attendance history queries';



CREATE INDEX "idx_tracker_date" ON "public"."tracker" USING "btree" ("date" DESC) WHERE ("status" IS NOT NULL);



CREATE INDEX "idx_tracker_semester_year" ON "public"."tracker" USING "btree" ("auth_user_id", "semester", "year", "date" DESC);



COMMENT ON INDEX "public"."idx_tracker_semester_year" IS 'Enables fast filtering of tracker records by academic semester and year';



CREATE INDEX "idx_tracker_user_status" ON "public"."tracker" USING "btree" ("auth_user_id", "status");



COMMENT ON INDEX "public"."idx_tracker_user_status" IS 'Optimizes queries filtering tracker records by user and status (correction/extra)';



CREATE INDEX "idx_user_settings_target" ON "public"."user_settings" USING "btree" ("target_percentage", "bunk_calculator_enabled");



COMMENT ON INDEX "public"."idx_user_settings_target" IS 'Enables analytics queries on user preference distributions';



CREATE INDEX "idx_users_auth_email" ON "public"."users" USING "btree" ("auth_id", "email") WHERE ("auth_id" IS NOT NULL);



COMMENT ON INDEX "public"."idx_users_auth_email" IS 'Speeds up user lookups by auth_id with email joins';



CREATE INDEX "idx_users_auth_id" ON "public"."users" USING "btree" ("auth_id");



CREATE INDEX "idx_users_sync_priority" ON "public"."users" USING "btree" ("last_synced_at" NULLS FIRST) WHERE ("ezygo_token" IS NOT NULL);



COMMENT ON INDEX "public"."idx_users_sync_priority" IS 'Optimizes cron sync queries that order by last_synced_at for users with tokens';



CREATE OR REPLACE TRIGGER "enforce_225_attendance_limit" BEFORE INSERT OR UPDATE ON "public"."tracker" FOR EACH ROW WHEN (("new"."attendance" = (225)::numeric)) EXECUTE FUNCTION "public"."check_225_attendance_limit"();



CREATE OR REPLACE TRIGGER "handle_updated_at" BEFORE UPDATE ON "public"."users" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');



ALTER TABLE ONLY "public"."contact_messages"
    ADD CONSTRAINT "contact_messages_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."notification"
    ADD CONSTRAINT "notification_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."tracker"
    ADD CONSTRAINT "tracker_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Anyone can insert contact messages" ON "public"."contact_messages" FOR INSERT WITH CHECK (true);



CREATE POLICY "Service Role Full Access" ON "public"."notification" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Service Role Full Access" ON "public"."tracker" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Service Role Full Access" ON "public"."user_settings" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Service Role Full Access" ON "public"."users" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Users can delete own tracker" ON "public"."tracker" FOR DELETE USING (("auth_user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can insert own notifications" ON "public"."notification" FOR INSERT WITH CHECK (("auth_user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can insert own profile" ON "public"."users" FOR INSERT WITH CHECK (("auth_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can insert own settings" ON "public"."user_settings" FOR INSERT WITH CHECK (("user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can insert own tracker" ON "public"."tracker" FOR INSERT WITH CHECK (("auth_user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can read own notification" ON "public"."notification" FOR SELECT USING (("auth_user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can read own profile" ON "public"."users" FOR SELECT TO "authenticated" USING (("auth_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can read own tracker" ON "public"."tracker" FOR SELECT USING (("auth_user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can see own messages" ON "public"."contact_messages" FOR SELECT TO "authenticated" USING (("user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can update own notifications" ON "public"."notification" FOR UPDATE USING (("auth_user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can update own profile" ON "public"."users" FOR UPDATE TO "authenticated" USING (("auth_id" = ( SELECT "auth"."uid"() AS "uid"))) WITH CHECK (("auth_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can update own settings" ON "public"."user_settings" FOR UPDATE USING (("user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can view own settings" ON "public"."user_settings" FOR SELECT USING (("user_id" = ( SELECT "auth"."uid"() AS "uid")));



ALTER TABLE "public"."contact_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notification" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tracker" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
































































































































































































GRANT ALL ON FUNCTION "public"."check_225_attendance_limit"() TO "anon";
GRANT ALL ON FUNCTION "public"."check_225_attendance_limit"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."check_225_attendance_limit"() TO "service_role";



GRANT ALL ON FUNCTION "public"."delete_user_account"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_user_account"() TO "service_role";
























GRANT ALL ON TABLE "public"."contact_messages" TO "anon";
GRANT ALL ON TABLE "public"."contact_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."contact_messages" TO "service_role";



GRANT ALL ON TABLE "public"."notification" TO "anon";
GRANT ALL ON TABLE "public"."notification" TO "authenticated";
GRANT ALL ON TABLE "public"."notification" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notification_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notification_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notification_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tracker" TO "anon";
GRANT ALL ON TABLE "public"."tracker" TO "authenticated";
GRANT ALL ON TABLE "public"."tracker" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tracker_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tracker_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tracker_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_settings" TO "anon";
GRANT ALL ON TABLE "public"."user_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."user_settings" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop trigger if exists "objects_delete_delete_prefix" on "storage"."objects";

drop trigger if exists "objects_insert_create_prefix" on "storage"."objects";

drop trigger if exists "objects_update_create_prefix" on "storage"."objects";

drop trigger if exists "prefixes_create_hierarchy" on "storage"."prefixes";

drop trigger if exists "prefixes_delete_hierarchy" on "storage"."prefixes";


  create policy "Authenticated User Upload"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Public Read Access"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "User Delete Own File"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'avatars'::text) AND (owner = auth.uid())));



  create policy "User Update Own File"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'avatars'::text) AND (owner = auth.uid())));


CREATE TRIGGER protect_buckets_delete BEFORE DELETE ON storage.buckets FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();

CREATE TRIGGER protect_objects_delete BEFORE DELETE ON storage.objects FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();


