-- INTEG-02: Revoke over-permissive GRANT ALL from the anon role
--
-- The baseline migration (20260217174834_remote_schema.sql) was generated by
-- `supabase db pull` and grants GRANT ALL on every table to anon, authenticated,
-- and service_role.  This mirrors the Supabase default-project template, which
-- relies entirely on RLS to restrict access.  While RLS protects these tables
-- today, GRANT ALL to anon violates the principle of least privilege at the
-- PostgreSQL layer: a missing or disabled RLS policy would expose all rows to
-- unauthenticated requests.
--
-- Principle applied:
--   - anon (unauthenticated Supabase requests) should have NO privileges on
--     tables that contain user data.  All legitimate access goes through the
--     `authenticated` role (JWT-validated) or `service_role` (server-side).
--   - The only exception is `contact_messages`, which has an open INSERT RLS
--     policy ("Anyone can insert contact messages") to support the public
--     contact form submitted by unauthenticated visitors.  anon therefore
--     needs INSERT only on that table.
--
-- Tables affected:
--   users            – user profile data (PII, encrypted tokens)
--   tracker          – per-user manual attendance records
--   notification     – per-user in-app notifications
--   user_settings    – per-user preferences
--   contact_messages – public contact form submissions (INSERT kept for anon)
--
-- Sequences affected:
--   tracker_id_seq      – identity sequence for tracker.id
--   notification_id_seq – identity sequence for notification.id
--   (no sequence on contact_messages – id is uuid DEFAULT gen_random_uuid())

-- Step 1: Remove all privileges for anon on user-data tables
REVOKE ALL ON TABLE "public"."users"            FROM "anon";
REVOKE ALL ON TABLE "public"."tracker"          FROM "anon";
REVOKE ALL ON TABLE "public"."notification"     FROM "anon";
REVOKE ALL ON TABLE "public"."user_settings"    FROM "anon";

-- Step 2: Remove anon access to identity sequences for the tables above
REVOKE ALL ON SEQUENCE "public"."tracker_id_seq"      FROM "anon";
REVOKE ALL ON SEQUENCE "public"."notification_id_seq" FROM "anon";

-- Step 3: Narrow contact_messages privileges: remove all then restore INSERT only
--         (the "Anyone can insert contact messages" RLS policy uses WITH CHECK (true)
--          and no TO clause, so it applies to all roles including anon)
REVOKE ALL    ON TABLE "public"."contact_messages" FROM "anon";
GRANT  INSERT ON TABLE "public"."contact_messages"  TO  "anon";

-- Step 4: Remove over-permissive default privileges for anon on future objects
--         The baseline schema sets ALTER DEFAULT PRIVILEGES GRANT ALL ON
--         TABLES/SEQUENCES TO anon.  Without revoking those defaults, any new
--         tables or sequences created by later migrations would again give anon
--         full access.  Explicitly revoke them so anon gets no privileges on
--         future objects by default.
ALTER DEFAULT PRIVILEGES IN SCHEMA "public"
    REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES IN SCHEMA "public"
    REVOKE ALL ON SEQUENCES FROM "anon";
