name: Deploy Supabase

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6.0.2

      - uses: supabase/setup-cli@0abc813ee30fc6710a975fb92db02aa8a6b14501 # v1.6.0
        with:
          version: 2.76.10

      - name: Link Project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy Database Changes (Migrations)
        run: supabase db push
